# Generated by Django 3.1.1 on 2020-10-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('conversion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_curr', models.CharField(max_length=45)),
                ('to_curr', models.CharField(max_length=45)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
    ]
