# Generated by Django 3.1.1 on 2020-10-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_currencyconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='conversion_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
