# Generated by Django 3.1.1 on 2020-12-07 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('country', django_countries.fields.CountryField(default='SG', max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.PositiveIntegerField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(choices=[('C', 'Customer'), ('S', 'Supplier'), ('A', 'Admin')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
