# Generated by Django 3.1.1 on 2020-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_desc', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
