# Generated by Django 3.1.1 on 2020-10-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prod_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prod_image', models.FileField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_category', to='products.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_supplier', to='products.supplier')),
            ],
        ),
    ]
