# Generated by Django 3.1.1 on 2020-10-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_prod', to='products.product')),
            ],
        ),
    ]
