# Generated by Django 3.1.1 on 2020-10-14 15:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=django_countries.fields.CountryField(default='SG', max_length=2),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
